language: r
cache: packages
dist: xenial
r:
  - oldrel
  - release
  - devel
addons:
  apt:
    sources:
      - sourceline: 'ppa:cran/jq'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
    - libudunits2-dev
    - libv8-dev
    - libprotobuf-dev
    - libprotoc-dev
    - libproj-dev
    - libgeos-dev
    - libgdal-dev
    - protobuf-compiler
    - valgrind
    - libpq-dev
    - libjq-dev
    - netcdf-bin
after_success:
  - Rscript -e 'covr::codecov()'
