language: r
cache: packages
dist: trusty
r:
  - oldrel
  - release
  - devel
addons:
  apt:
    packages:
    - libv8-dev
    - libgdal1-dev
    - libgdal-dev
    - libgeos-c1
    - libproj-dev
after_success:
  - Rscript -e 'covr::codecov()'
