language: r
cache: packages
dist: trusty
r:
  - oldrel
  - release
  - devel
r_github_packages:
  - crunch-io/rcrunch@geo
addons:
  apt:
    packages:
    - libv8-dev
    - libgdal1-dev
    - libgdal-dev
    - libgeos-c1
    - libproj-dev
    - libspatialite-dev
    - libgdal20
    - libspatialite5
after_success:
  - Rscript -e 'covr::codecov()'
